name: Publish Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: |
          yarn install
      - name: Install GitHub Pages
        run: |
          npm install -g gh-pages@3.0.0
      - name: Build Website
        run: |
          yarn build
          echo "tractor-v2.samples.piral.cloud" > packages/app/dist/release/CNAME
          cp packages/app/dist/release/index.html packages/app/dist/release/404.html
      - name: Deploy Website
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          gh-pages -d "packages/app/dist/release" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
